# Generated by Django 3.2 on 2025-10-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='collect',
            name='scenic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.scenicinfo'),
        ),
        migrations.AlterField(
            model_name='scenicinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
