# Generated by Django 3.2 on 2025-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20251017_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='user_faces/'),
        ),
    ]
